name    'bitlancer-sudo'
version '0.0.1'
source 'https://github.com/Bitlancer/puppet-sudo'
author 'Bitlancer LLC (contact@bitlancer.com)'
license 'Apache License, Version 2.0'
summary 'A sudo Puppet Module'
description 'A sudo Puppet Module with SSSD backend'
project_page 'https://github.com/Bitlancer/puppet-sudo'
